"""empty message

Revision ID: 1e65423002be
Revises: 7958bdb891da
Create Date: 2020-01-21 12:08:48.428722

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e65423002be'
down_revision = '7958bdb891da'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('type_post', sa.String(), nullable=True))
    op.add_column('post', sa.Column('url', sa.String(), nullable=True))
    op.drop_column('post', 'image')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('post', sa.Column('image', sa.VARCHAR(), nullable=True))
    op.drop_column('post', 'url')
    op.drop_column('post', 'type_post')
    # ### end Alembic commands ###
