"""empty message

Revision ID: 4caaa322ea15
Revises: 6719dcaceb17
Create Date: 2020-01-07 20:12:57.422100

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '4caaa322ea15'
down_revision = '6719dcaceb17'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_posts_image', table_name='posts')
    op.drop_index('ix_posts_text', table_name='posts')
    op.drop_index('ix_posts_title', table_name='posts')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('ix_posts_title', 'posts', ['title'], unique=False)
    op.create_index('ix_posts_text', 'posts', ['text'], unique=False)
    op.create_index('ix_posts_image', 'posts', ['image'], unique=False)
    # ### end Alembic commands ###
