"""empty message

Revision ID: 6719dcaceb17
Revises: 788d19ad2141
Create Date: 2020-01-07 20:02:40.090528

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6719dcaceb17'
down_revision = '788d19ad2141'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('posts', sa.Column('timestamp', sa.DateTime(), nullable=True))
    op.create_index(op.f('ix_posts_timestamp'), 'posts', ['timestamp'], unique=False)
    op.drop_index('ix_posts_image', table_name='posts')
    op.create_index(op.f('ix_posts_image'), 'posts', ['image'], unique=False)
    op.drop_index('ix_posts_text', table_name='posts')
    op.create_index(op.f('ix_posts_text'), 'posts', ['text'], unique=False)
    op.drop_index('ix_posts_title', table_name='posts')
    op.create_index(op.f('ix_posts_title'), 'posts', ['title'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_posts_title'), table_name='posts')
    op.create_index('ix_posts_title', 'posts', ['title'], unique=1)
    op.drop_index(op.f('ix_posts_text'), table_name='posts')
    op.create_index('ix_posts_text', 'posts', ['text'], unique=1)
    op.drop_index(op.f('ix_posts_image'), table_name='posts')
    op.create_index('ix_posts_image', 'posts', ['image'], unique=1)
    op.drop_index(op.f('ix_posts_timestamp'), table_name='posts')
    op.drop_column('posts', 'timestamp')
    # ### end Alembic commands ###
