"""empty message

Revision ID: 83c0982507c5
Revises: 9137c22339e1
Create Date: 2020-01-22 23:09:04.720206

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '83c0982507c5'
down_revision = '9137c22339e1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image')
    op.add_column('project', sa.Column('type_project', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'type_project')
    op.add_column('post', sa.Column('image', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
