"""empty message

Revision ID: afefc796c089
Revises: fc4b3bd6f52a
Create Date: 2020-01-24 23:33:45.534235

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'afefc796c089'
down_revision = 'fc4b3bd6f52a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('post', 'image')
    op.add_column('project', sa.Column('blurb', sa.String(), nullable=True))
    op.add_column('project', sa.Column('type_project', sa.String(), nullable=True))
    op.add_column('project', sa.Column('url', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('project', 'url')
    op.drop_column('project', 'type_project')
    op.drop_column('project', 'blurb')
    op.add_column('post', sa.Column('image', sa.VARCHAR(), nullable=True))
    # ### end Alembic commands ###
